FROM node:20-slim

LABEL org.opencontainers.image.description "ACDH-CH frontend devcontainer"

RUN corepack enable

ENV DEBIAN_FRONTEND=noninteractive

# playwright dependencies
RUN \
  apt-get update \
  && apt-get install --no-install-recommends -y \
    libglib2.0-0 \
    libnss3 \
    libnspr4 \
    libdbus-1-3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxcb1 \
    libxkbcommon0 \
    libatspi2.0-0 \
    libx11-6 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libpango-1.0-0 \
    libcairo2 \
    libasound2 \
  && apt-get clean
